
# Logging
logging.level.root=INFO
logging.level.com.example.usersm=DEBUG
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/application_prod.log

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/usersm?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Server
server.port=8080

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG


management.endpoints.web.exposure.include=*
# File Upload
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS,Asia/Kolkata
logging.level.org.flywaydb=DEBUG